## Notebook 7: Race Strategy Prediction System
Use the trained Random Forest model to predict lap times for new race scenarios and provide simple strategy insights.

In [1]:
import pandas as pd
import numpy as np
import joblib

In [2]:
# loading the trained model

model = joblib.load("../models/best_model.pkl")

In [11]:
# creating the sample race scenario (instead of using the training data , creating new examples)

sample_data = pd.DataFrame({
    "LapNumber": [10, 25, 50],
    "TyreLife": [1, 14, 24],
    "Stint": [1, 2, 3],
    "Position": [1, 3, 5],
    "TrackStatus": [1, 1, 1],
    "FuelLoadApprox": [0.80, 0.55, 0.30],
    "StintProgress": [0.20, 0.60, 0.95],
    "CompoundEncoded": [0, 1, 2],
    "FreshTyre": [1, 0, 0],
    "TyreAgeSquared": [1, 196, 576]
})

sample_data

,LapNumber,TyreLife,Stint,Position,TrackStatus,FuelLoadApprox,StintProgress,CompoundEncoded,FreshTyre,TyreAgeSquared
0,10,1,1,1,1,0.80,0.20,0,1,1
1,25,14,2,3,1,0.55,0.60,1,0,196
2,50,24,3,5,1,0.30,0.95,2,0,576

In [12]:
# predicting the lap times

sample_data["PredictedLapTime"] = model.predict(sample_data)
sample_data

,LapNumber,TyreLife,Stint,Position,TrackStatus,FuelLoadApprox,StintProgress,CompoundEncoded,FreshTyre,TyreAgeSquared,PredictedLapTime
0,10,1,1,1,1,0.80,0.20,0,1,1,119.166038
1,25,14,2,3,1,0.55,0.60,1,0,196,89.536812
2,50,24,3,5,1,0.30,0.95,2,0,576,93.731520

In [13]:
# adding a simple strategy recommendation

def recommend_pitstop(row):
    if row["StintProgress"] > 0.85:
        return "Pit Recommended"

    if row["FreshTyre"] == 1:
        return "Stay Out"

    return "Monitor Tyres"

sample_data["Recommendation"] = sample_data.apply(
    recommend_pitstop,
    axis=1
)

sample_data

,LapNumber,TyreLife,Stint,Position,TrackStatus,FuelLoadApprox,StintProgress,CompoundEncoded,FreshTyre,TyreAgeSquared,PredictedLapTime,Recommendation
0,10,1,1,1,1,0.80,0.20,0,1,1,119.166038,Stay Out
1,25,14,2,3,1,0.55,0.60,1,0,196,89.536812,Monitor Tyres
2,50,24,3,5,1,0.30,0.95,2,0,576,93.731520,Pit Recommended

In [14]:
sample_data.to_csv(
    "../outputs/tables/strategy_predictions.csv",
    index=False
)

sample_data

,LapNumber,TyreLife,Stint,Position,TrackStatus,FuelLoadApprox,StintProgress,CompoundEncoded,FreshTyre,TyreAgeSquared,PredictedLapTime,Recommendation
0,10,1,1,1,1,0.80,0.20,0,1,1,119.166038,Stay Out
1,25,14,2,3,1,0.55,0.60,1,0,196,89.536812,Monitor Tyres
2,50,24,3,5,1,0.30,0.95,2,0,576,93.731520,Pit Recommended